### ISSUE TITLE
Problems with Autofac 5.1.2

### ISSUE THREAD

**Issue by tallalkazmi** [erangil2/autofac.log4net#4]
I believe something has changed in newer versions of Autofac i.e. > 4.9.4. Log4NetModule does not injects and throws no exceptions either. Can you please investigate this? I am using this package for over 6 applications on production and when I update Autofac, logger stops working. Thanks.

**Comment by eran-gil** [comment]
Hey, I found the problem, Autofac made breaking changes in version 5.
Fixed it and uploaded versions 2.0.0.1 that supports Autofac version 5 and above.
From now on there won't be any support for .net versions below 4.6.1 and autofac versions below 5.
If you find this project helpful feel free to "Star" it :)

**Comment by tallalkazmi** [comment]
Thanks a lot. :)
